services:
  catalogo-service:
    build: ./catalogo-service
    image: lucashiratuca/catalogo-service:latest
    container_name: catalogo_service
    restart: always
    ports:
      - "8217:3000"
    env_file:
      - .env
    environment:
      - AUTH_SERVICE_URL=http://auth-service:4000
      - CATALOG_PUBLIC_URL=http://localhost:8217
      - LOG_SERVICE_URL=http://log-service:5000
      - S3_ENDPOINT=garage:3900
      - S3_ACCESS_KEY=GK9ae6ab4a2d12a3227b1a0d9a
      - S3_SECRET_KEY=f46bb999a2d2615ad200369932ccff5454f113c74c4614e6027dc2380dcc5632
      - S3_BUCKET=perfis
      - S3_REGION=garage
    networks:
      - app_network
    depends_on:
      - auth-service
      - log-service
      - garage

  auth-service:
    build: ./auth-service
    image: lucashiratuca/auth-service:latest
    container_name: auth_service
    restart: always
    env_file:
      - .env
    environment:
      - LOG_SERVICE_URL=http://log-service:5000
    networks:
      - app_network
    depends_on:
      - log-service

  log-service:
    build: ./log-service
    image: lucashiratuca/log-service:latest
    container_name: log_service
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app_network
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis_audit
    restart: always
    networks:
      - app_network
    volumes:
      - redis_data:/data

  garage:
    image: dxflrs/garage:v1.0.1
    container_name: garage_s3
    restart: always
    ports:
      - "3900:3900" # S3 API
      - "3902:3902" # S3 Web
      - "3903:3903" # Admin API
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
      - garage_meta:/var/lib/garage/meta
      - garage_data:/var/lib/garage/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  redis_data:
  garage_meta:
  garage_data: